# Site settings
title: AmandaNeumann.com
email: amandaneumann@me.com
description: Random thoughts from an educationalist turned apprentice code ninja.
baseurl: /amanda_blog # the subpath of your site, e.g. /blog/
url: "http://amanda08.github.io" # the base hostname & protocol for your site
twitter_username: amandamelb
github_username:  amanda08

# Build settings
markdown: kramdown
